pipeline:
  tests:
    image: node:10
    commands:
      - yarn
      - npm run test
  build:
    image: node:10
    secrets: [ github_token ]
    commands:
      - yarn
      - npx prebuild --all -t  -u $GITHUB_TOKEN
    when:
      event: [ tag ]
  publish_npm:
    image: plugins/npm
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      event: [ tag ]