pipeline:
  tests:
    image: node:${NODE_VERSION}
    environment:
      - NODE_ENV=test
    commands:
      - node -v
      - yarn -v
      - uname -r
      - yarn install --ignore-engines
      - yarn test
  build:
    image: node:${NODE_VERSION}
    secrets: [ github_token ]
    commands:
      - if [ "$NODE_VERSION" != "10" ]; then exit; fi
      - yarn
      - npx prebuild --all -t  -u $GITHUB_TOKEN
    when:
      event: [ tag ]
  publish_npm:
    image: plugins/npm
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      event: [ tag ]
matrix:
  NODE_VERSION:
    - 4
    - 6
    - 8
    - 10
    - 11